name: istio-envoy
"on":
  push:
    paths:
    - .github/workflows/zz-istio-envoy.yml
    - build/istio-envoy/Dockerfile.istio-envoy
    - build/istio-envoy/Dockerfile.version
    - build/istio-envoy/Makefile
jobs:
  istio-envoy:
    runs-on:
    - self-hosted
    - linux
    - ARM64
    defaults:
      run:
        working-directory: build/istio-envoy
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - uses: docker/login-action@v1
      name: Login ghcr.io
      with:
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
    - uses: docker/login-action@v1
      name: Login docker.io
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
    - id: prepare
      name: prepare
      env:
        NAME: istio-envoy
      run: |-
        if [[ ${{ github.ref }} != "refs/heads/master" ]]; then
          export TAG=temp-${{ github.sha }}
        fi
        make prepare
    - uses: docker/build-push-action@v2
      name: Push
      with:
        build-args: ${{ steps.prepare.outputs.build_args }}
        context: build/istio-envoy
        file: build/istio-envoy/Dockerfile.istio-envoy
        labels: |-
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |-
          ghcr.io/querycap/istio/${{ steps.prepare.outputs.image }}
          docker.io/querycapistio/${{ steps.prepare.outputs.image }}
