name: istio-proxyv2
"on":
  push:
    paths:
    - .github/workflows/zz-istio-proxyv2.yml
    - build/istio/Dockerfile.proxyv2
    - build/istio/Dockerfile.version
    - build/istio/Makefile
jobs:
  proxyv2:
    runs-on:
    - ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
        - 5000:5000
    defaults:
      run:
        working-directory: build/istio
    strategy:
      matrix:
        BASE_DISTRIBUTION:
        - default
        - distroless
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - uses: docker/login-action@v1
      name: Login ghcr.io
      with:
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
    - uses: docker/login-action@v1
      name: Login docker.io
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
    - id: prepare
      name: prepare
      env:
        BASE_DISTRIBUTION: ${{ matrix.BASE_DISTRIBUTION }}
        NAME: proxyv2
      run: |-
        if [[ ${{ github.ref }} != "refs/heads/master" ]]; then
          export TAG=temp-${{ github.sha }}
        fi
        make prepare
    - uses: docker/build-push-action@v2
      name: Push
      with:
        build-args: ${{ steps.prepare.outputs.build_args }}
        context: build/istio
        file: build/istio/Dockerfile.proxyv2
        labels: |-
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |-
          ghcr.io/querycap/istio/${{ steps.prepare.outputs.image }}
          docker.io/querycapistio/${{ steps.prepare.outputs.image }}
