name: istio-base
"on":
  push:
    paths:
    - .github/workflows/zz-istio-base.yml
    - build/istio-base/Dockerfile.istio-base
    - build/istio-base/Dockerfile.version
    - build/istio-base/Makefile
jobs:
  istio-base:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: build/istio-base
    outputs:
      image: ${{ steps.prepare.outputs.image }}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - uses: docker/login-action@v1
      name: Login ghcr.io
      with:
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
    - uses: docker/login-action@v1
      name: Login docker.io
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
    - id: prepare
      name: Prepare
      env:
        GITHUB_REF: ${{ github.sha }}
        GITHUB_SHA: ${{ github.ref }}
        NAME: istio-base
      run: |-
        echo ::set-output name=target_platforms::linux/amd64,linux/arm64

        if [[ ${GITHUB_REF} != "refs/heads/master" ]]; then
          export TAG=sha-${GITHUB_SHA::7}
        fi

        make prepare
    - uses: docker/build-push-action@v2
      name: Build & May Push
      with:
        build-args: ${{ steps.prepare.outputs.build_args }}
        context: build/istio-base
        file: build/istio-base/Dockerfile.istio-base
        labels: |-
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
        platforms: ${{ steps.prepare.outputs.target_platforms }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: |-
          ghcr.io/querycap/istio/${{ steps.prepare.outputs.image }}${{ steps.prepare.outputs.image_suffix }}
          docker.io/querycapistio/${{ steps.prepare.outputs.image }}${{ steps.prepare.outputs.image_suffix }}
