name: zz-sync-proxyv2
"on":
  push:
    paths:
    - .github/workflows/zz-sync-proxyv2.yml
    - sync/Dockerfile.proxyv2,arm64
jobs:
  sync:
    runs-on:
    - self-hosted
    - arm64
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_MIRROR_PASSWORD }}
        registry: ${{ secrets.DOCKER_MIRROR_REGISTRY }}
        username: ${{ secrets.DOCKER_MIRROR_USERNAME }}
    - run: |-
        DOCKERFILE=sync/Dockerfile.proxyv2,arm64
        TAG=$(cat ${DOCKERFILE} | grep "^FROM " | sed -e "s/FROM //g" | head -1)
        make -f ./build/Makefile buildx TAGS=${{ secrets.DOCKER_MIRROR_REGISTRY }}/${TAG} DOCKERFILE=${DOCKERFILE}
