name: tempo-tempo-query
"on":
  push:
    paths:
    - .github/workflows/zz-tempo-tempo-query.yml
    - build/tempo/Dockerfile.tempo-query
    - build/tempo/Dockerfile.version
    - build/tempo/Makefile
jobs:
  tempo-query:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: build/tempo
    outputs:
      image: ${{ steps.prepare.outputs.image }}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - uses: docker/login-action@v1
      name: Login ghcr.io
      with:
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
    - uses: docker/login-action@v1
      name: Login docker.io
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
    - name: Build && May push
      env:
        DOCKERX_LABELS: org.opencontainers.image.source=https://github.com/${{ github.repository }} org.opencontainers.image.revision=${{ github.sha }}
        DOCKERX_NAME: tempo-query
        DOCKERX_PLATFORMS: linux/amd64 linux/arm64
        DOCKERX_PUSH: ${{ github.event_name != 'pull_request' }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_SHA: ${{ github.sha }}
        HUB: ghcr.io/querycap/istio docker.io/querycapistio
      run: |-
        if [[ ${GITHUB_REF} != "refs/heads/master" ]]; then
          export DOCKERX_TAGS=sha-${GITHUB_SHA::7}
        fi
        make dockerx
